Add db migration launch
demarque/github-action-templates pull request #38
Opened 2024-01-31 20:30 UTC by roxannelandry

2024-01-31 20:30 UTC, roxannelandry commented on .github/workflows/template-docker-build.yaml
> +          echo "DB Migration"
A voir selon ce qu'on decide du bord de l'infra

2024-02-02 17:34 UTC, vfiset commented on .github/workflows/template-docker-build.yaml
> +                  sed -i 's/enableDbMigration: [a-z]*/enableDbMigration: true/g' modules/${module}/charts/${product_name}/${{ inputs.TARGET_ENV }}${{ inputs.TARGET_EXTRA_ARGS }}*.yaml
```suggestion
                  sed -i 's/runDbMigrationHook: [a-z]*/enableDbMigration: true/g' modules/${module}/charts/${product_name}/${{ inputs.TARGET_ENV }}${{ inputs.TARGET_EXTRA_ARGS }}*.yaml
```

2024-02-02 18:59 UTC, vfiset requested changes
un peu de nitpick mais c'est LGTM a part ca !

2024-02-02 18:59 UTC, vfiset commented on .github/workflows/template-docker-build.yaml
> +      DB_MIGRATION_ENABLE:
```suggestion
      DB_MIGRATION_ENABLED:
```

2024-02-02 18:59 UTC, vfiset commented on .github/workflows/template-docker-build.yaml
> +        description: The path to the folder where the db is define in the repository
```suggestion
        description: The pattern matching db migration files location in the repository
```

2024-02-02 18:59 UTC, vfiset commented on .github/workflows/template-docker-build.yaml
> +      - name: Filter DB Migration In Repository Changes
```suggestion
      - name: Filter DB Migration in Repository Changes
```

2024-02-02 18:59 UTC, vfiset commented on .github/workflows/template-docker-build.yaml
> +                echo
```suggestion
```

2024-02-02 18:59 UTC, vfiset commented on .github/workflows/template-docker-build.yaml
> +                    echo "Will run DB migration"
```suggestion
                    echo "Will run DB migration hook"
```

2024-02-02 18:59 UTC, vfiset commented on .github/workflows/template-docker-build.yaml
> +                    echo "Will not run DB migration"
```suggestion
                    echo "Will not run DB migration hook"
```

2024-02-02 19:16 UTC, vfiset requested changes

2024-02-02 19:16 UTC, vfiset commented on .github/workflows/template-docker-build.yaml
> +      - name: Checkout Repository
faudrait enlever le checkout qu'on faisait deja a la ligne 284

2024-02-02 19:29 UTC, vfiset approved these changes

2024-02-02 19:29 UTC, merged